### ISSUE TITLE
matlab.engine.MatlabExecutionError with Selective Search

### ISSUE THREAD

**Issue by tomrunia** [myfavouritekk/TPN#7]
With a lot of effort I've compiled everything and I am now trying to get the tubes for an example video. However, I get stuck at generating the proposals using **vdetlib** (see the stacktrace below). A quick search indicates that there is no `External/selective_search_python` somewhere in the directory. How do I continue to generate the proposals? 

I've tried creating the path `External/selective_search_python` but then I get the error: `Undefined function or variable 'selective_search'.`. Any help would be appreciated :-)

```
(python2-cv2) user@machine ~/dev/lib $ python TPN/external/vdetlib/tools/vid_proposals.py /home/USER/experiments/2017/tmp/001_trampoline.vid /home/USER/experiments/2017/tmp/001_trampoline.proposals
Error using cd
Cannot CD to /home/USER/dev/lib/External/selective_search_python (Name is nonexistent or not a directory).

Traceback (most recent call last):
  File "TPN/external/vdetlib/tools/vid_proposals.py", line 16, in <module>
    box_proto = vid_proposals(vid_proto)
  File "./vdetlib/vdet/proposal.py", line 39, in vid_proposals
    proposals = get_windows(frame_names, method)
  File "./vdetlib/vdet/proposal.py", line 25, in get_windows
    all_boxes = matlab_engine(script, image_fnames)
  File "./vdetlib/utils/common.py", line 343, in matlab_engine
    eng.cd(script_dirname)
  File "/usr/local/MATLAB/R2015a/extern/engines/python/build/lib.linux-x86_64-2.7/matlab/engine/matlabengine.py", line 79, in __call__
    _stderr).result()
  File "/usr/local/MATLAB/R2015a/extern/engines/python/build/lib.linux-x86_64-2.7/matlab/engine/futureresult.py", line 107, in result
    self._future,self._nargout, None, out=self._out, err=self._err)
matlab.engine.MatlabExecutionError: Cannot CD to /home/USER/dev/lib/External/selective_search_python (Name is nonexistent or not a directory).
```

**Comment by amf272** [comment]
I was able to bypass this by cloning ![https://github.com/sergeyk/selective_search_ijcv_with_python](https://github.com/sergeyk/selective_search_ijcv_with_python) into a directory named External and renaming the cloned directory (selective_search_ijcv_with_python) to selective_search_python.
